## Week 1: Data Structures - Part1 - Assignment 
**by Sarthak Niwate (Intern at Chistats)**

In [2]:
import numpy as np
import math

#### 1. Write short notwe on below 

    Arithmetic operators
    Assignment operators
    Comparison operators
    Logical operators
    Identity operators
    Membership operators
    Bitwise operators

1. Arithmetic Operators

| Operator | Meaning | Example | 
| :--- | :---: | ---: |
|+ | Add two operands or unary plus | x + y+ 2 |
|-|Subtract right operand from the left or unary minus|x - y- 2|
|*|Multiply two operands|x * y|
|/|Divide left operand by the right one (always results into float)|x / y|
|%|Modulus - remainder of the division of left operand by the right|x % y (remainder of x/y)|
|//|Floor division - division that results into whole number adjusted to the left in the number line|x // y|
|**|Exponent - left operand raised to the power of right|x**y (x to the power y)|

2. Assignment Operators

|Operator|	Example	|Equivalent to| 
| :--- | :---: | ---: |
|=	|x = 5|	x = 5|
|+=|	x += 5	|x = x + 5|
|-=	|x -= 5|	x = x - 5|
|*=	|x *= 5	|x = x * 5|
|I=	|x I= 5|	x = x I 5|
|%=	|x %= 5	|x = x % 5|
| II=	|x II= 5|	x = x II 5|
|**=	|x **= 5	|x = x ** 5|
|&=	|x &= 5	|x = x & 5|
|I=	|x I= 5|	x = x I 5|
|^=|	x ^= 5	|x = x ^ 5|
|>>=	|x >>= 5	|x = x >> 5|
|<<=	|x <<= 5	|x = x << 5|

3. Comparison Operators

| Operator | Meaning | Example | 
| :--- | :---: | ---: |
|>	|Greater than - True if left operand is greater than the right|	x > y|
|<	|Less than - True if left operand is less than the right	|x < y|
|==	|Equal to - True if both operands are equal	|x == y|
|!=	|Not equal to - True if operands are not equal	|x != y|
|>=	|Greater than or equal to - True if left operand is greater than or equal to the right|	x >= y|
|<=	|Less than or equal to - True if left operand is less than or equal to the right|	x <= y|

4. Logical Operators

| Operator | Meaning | Example | 
| :--- | :---: | ---: |
|and	|True if both the operands are true|	x and y|
|or	|True if either of the operands is true|	x or y|
|not	|True if operand is false (complements the operand)|	not x|

5. Identity Operators

| Operator| Meaning                                 | Example       |
| :---    | :---:                                   | ---:           |
| is      | True if the operands are identical      | x is True     |
| is not  | True if the operands are not identical  | x is not True |


6. Membership Oerators 

| Operator| Meaning                                 | Example       |
| :---    | :---:                                   | ---:           |
| in      | True if the value is found in seuqence  | 5 in list3     |
| not in  | True if the value is not found in sequence  | 'a' not in list3 |


7. Bitwise Operators

| Operator| Meaning                                 | Example       |
| :---    | :---:                                   | ---:           |
|&	|Bitwise AND	|x & y = 0 (0000 0000)|
|I	|Bitwise OR|	x I y = 14 (0000 1110)|
|~	|Bitwise NOT	|~x = -11 (1111 0101)|
|^	|Bitwise XOR	|x ^ y = 14 (0000 1110)|
|>>	|Bitwise right shift|	x >> 2 = 2 (0000 0010)|
|<<	|Bitwise left shift|x << 2 = 40 (0010 1000)|

#### 2. Input : a = 20 b = 4

Note down the output of below operations 

    a+b
    a-b
    a*b
    a/b
    a//b
    a%b
    a**b

In [3]:
a = 20 
b = 4
print("a:", a, "b:", b)
print("a+b: ", a+b)
print("a-b: ", a-b)
print("a*b: ", a*b)
print("a/b: ", a/b)
print("a//b: ", a//b)
print("a%b: ", a%b)
print("a**b: ", a**b)

a: 20 b: 4
a+b:  24
a-b:  16
a*b:  80
a/b:  5.0
a//b:  5
a%b:  0
a**b:  160000


#### 3. Note down the output of below operations 

    Input : a = 10 b = 2
    a/b
    a//b

    Input : a = 10.0 b = 2
    a/b
    a//b

    Notedown the reason for having difference in decimal digits

In [4]:
a = 10
b = 2
print("a:", a, "b:", b)
print("a/b: ", a/b)
print("a//b: ", a//b)

a = 10.0 
b = 2
print("a:", a, "b:", b)
print("a/b: ", a/b)
print("a//b: ", a//b)

a: 10 b: 2
a/b:  5.0
a//b:  5
a: 10.0 b: 2
a/b:  5.0
a//b:  5.0


#### 4. Write short note on string concatination operator (+) and string multipication operator(*)

The string is an object in python, some cases you need a combined string. The one way to do it is Python String Concatenation with a ‘ + ” operator.  In a case where you want a merge a 2 string and store value in another variable then use new_String=  first_string + second_string. Python provides several ways to concatenate strings.

Ways to Python String Concatenation

    1. Plus – using ‘+’ operator
    2. Assign – using ‘+=’ operator
    3. Using % operator
    4. Multiple copies -Using * operator
    5. join() Function – For iterators
    
1. To add two string, we can simply use the + or add operator. As its name suggests, it can add two string and return a copy of the combined string. Using the + operator, we can combine multiple strings together.

In [5]:
str1 = 'Great'
str2 = ' Theme'
print(str1 + str2)

Great Theme


In [6]:
str1 = 'Superb '
 
print(str1*3)

Superb Superb Superb 


#### 5. Input : a = 20 b = 10

    Note down the output of below operations 
    a>b
    a>=b
    a<b
    a<=b

In [7]:
a = 20
b = 10
print("a:", a, "b:", b)
print("a>b: ", a>b)
print("a>=b: ", a>=b)
print("a<b: ", a<b)
print("a<=b: ", a<=b)

a: 20 b: 10
a>b:  True
a>=b:  True
a<b:  False
a<=b:  False


#### 5.a Input : a = "abc" b = "cde" c = "abc"
    Note down the output of below operations 
    a>b
    a>=b
    a<b
    a<=b

    a>c
    a>=c
    a<c
    a<=c

In [8]:
a = "abc" 
b = "cde" 
c = "abc"

print("a:", a, "b:", b)
print("a>b: ", a>b)
print("a>=b: ", a>=b)
print("a<b: ", a<b)
print("a<=b: ", a<=b)

print("\na:", a, "c:", c)
print("a>c: ", a>c)
print("a>=c ", a>=c)
print("a<c: ", a<c)
print("a<=c: ", a<=c)

a: abc b: cde
a>b:  False
a>=b:  False
a<b:  True
a<=b:  True

a: abc c: abc
a>c:  False
a>=c  True
a<c:  False
a<=c:  True


#### 6. Note down the output of below operations 

    Input a = 10 b = 20 c = 10 d = 10
    a==b
    a!=b
    a==c==d

    Input a = "abc" b = "cde" c = "abc" d = "abc"
    a==b
    a!=b
    a==c
    a!=c
    a==c==d

In [9]:
a = 10 
b = 20 
c = 10 
d = 10

print("a:", a, "b:", b, "c:", c, "d:", d)
print("a==b: ", a==b)
print("a!=b: ", a!=b)
print("a==c==d: ", a==c==d)

a = "abc" 
b = "cde" 
c = "abc" 
d = "abc"

print("\na:", a, "b:", b, "c:", c, "d:", d)
print("a==b: ", a==b)
print("a!=b: ", a!=b)
print("a==c: ", a==c)  
print("a!=c: ", a!=c)
print("a==c==d: ", a==c==d)

a: 10 b: 20 c: 10 d: 10
a==b:  False
a!=b:  True
a==c==d:  True

a: abc b: cde c: abc d: abc
a==b:  False
a!=b:  True
a==c:  True
a!=c:  False
a==c==d:  True


#### 7. Using logical operators: WAPTP "Student is passed" if he scores 40+ marks in both Physics and Maths

In [11]:
print("Exam Department Eligibility Page\n")
while True:
    try:
        Physics = float(input('Enter the Physics score: '))
        Maths = float(input('Enter the Maths score: '))
    except ValueError:
        print('\nEnter marks in correct format. Try Again!')
        pass
    else:
        print('\nThe expected marks format is correct')
        if Physics > 40 and Maths > 40:
            print("\nYou're Passed")
            break
        else:
            print("\nYou're not passed")
            break

Exam Department Eligibility Page

Enter the Physics score: 39
Enter the Maths score: 42

The expected marks format is correct

You're not passed


#### 8. Using logical operators: WAPTP "Student is failed" if he scores 40- marks in atleast one subject from Physics and Maths

In [12]:
print("Exam Department Eligibility Page\n")
while True:
    try:
        Physics = float(input('Enter the Physics score: '))
        Maths = float(input('Enter the Maths score: '))
    except ValueError:
        print('\nEnter marks in correct format. Try Again!')
        pass
    else:
        print('\nThe expected marks format is correct')
        if Physics > 40 or Maths > 40:
            print("\nYou're Passed")
            break
        else:
            print("\nYou're not passed")
            break

Exam Department Eligibility Page

Enter the Physics score: 52
Enter the Maths score: 39

The expected marks format is correct

You're Passed


#### 9. Using logical operators: WAPTP "Student is failed" if valus of isPassed is True then print "Student is passed" else print "Student is failed" 

In [13]:
isPassed = bool(input("Student is passed ? True/False: "))
 
if not(isPassed)== False:
    print("Sudent is passed")

Student is passed ? True/False: True
Sudent is passed


#### 10. Using bitwise operators:

    Input 	a = 10
            b = 20 
            c = 3
    WAPTP output of below 
    a&b
    a|b
    a^b
    (~a)
    a<<b
    c>>3

    True & False
    True | False
    True ^ False
    ~True
    True<<2
    True>>2

In [14]:
a = 10
b = 20 
c = 3

print("a&b: ", a&b)
print("a|b: ", a|b)
print("a^b: ", a^b)
print("(~a): ", (~a))
print("a<<b: ", a<<b)
print("c>>3: ", c>>3)

print("\nTrue & False: ", True & False)
print("True | False: ", True | False)
print("True ^ False: ", True ^ False)
print("~True: ", ~True)
print("True<<2: ", True<<2)
print("True>>2: ", True>>2)

a&b:  0
a|b:  30
a^b:  30
(~a):  -11
a<<b:  10485760
c>>3:  0

True & False:  False
True | False:  True
True ^ False:  True
~True:  -2
True<<2:  4
True>>2:  0


#### 11. Using Ternary operator or Conditional operator: Identify minimum of two numbers

In [15]:
n1_11 = 18
n2_11 = 32
if n1_11 < n2_11:
    print(n1_11)
else:
    print(n2_11)

18


#### 12. Using Ternary operator or Conditional operator: Identify minimum of three numbers

In [16]:
n1_12 = 18
n2_12 = 32
n3_12 = 12
if n1_12<n2_12 and n1_12<n3_12:
    print(n1_12)
elif n2_12<n1_12 and n2_12<n3_12:
    print(n2_12)
else:
    print(n3_12)

12


#### 13. Using Ternary operator or Conditional operator: Identify maximum of three numbers

In [17]:
n1_13 = 18
n2_13 = 32
n3_13 = 12

if n1_13>n2_13 and n1_13>n3_13:
    print(n1_13)
elif n2_13>n1_13 and n2_13>n3_13:
    print(n2_13)
else:
    print(n3_13)

32


#### 14. Special operators 
    Write note on Identity operator
    Write note on membership operator

| Operator| Meaning                                 | Example       |
| :---    | :---:                                   | ---:           |
|1. Identity Oerators |
| is      | True if the operands are identical      | x is True     |
| is not  | True if the operands are not identical  | x is not True |
|2. Membership Oerators |
| in      | True if the value is found in seuqence  | 5 in list3     |
| not in  | True if the value is not found in sequence  | 'a' not in list3 |

#### 15. Using Identity operator: WAPTP whether both variables are pointing to same addres or not
    1. a = 10 b = 10
    2. a = 20 b = 10
    3. a = ["one","two","three"] b = ["one","two","three"]

In [18]:
# The Python is and is not operators compare the identity of two objects. In CPython, this is their memory address. 
# Everything in Python is an object, and each object is stored at a specific memory location. 
# The Python is and is not operators check whether two variables refer to the same object in memory.

a = 10 
b = 10
print(a is b)


a = 20 
b = 10
print(a is b)

a = ["one","two","three"] 
b = ["one","two","three"]
print(a is b)

True
False
False


#### 16. Using membership operator: WAP to check whether blow string are present in str1 = "welcome to chistats pvt ltd"
    'a'
    'z'
    'x'
    'c'
    'd'
    'ltd'
    'chistats'

In [19]:
str1 = "welcome to chistats pvt ltd"

elements = ['a', 'z', 'x', 'c', 'd', 'ltd', 'chistats']

for i in elements:
    if i in str1:
        print(i, " is present in str1")
    else:
        print(i, " is not present in str1")

a  is present in str1
z  is not present in str1
x  is not present in str1
c  is present in str1
d  is present in str1
ltd  is present in str1
chistats  is present in str1


#### 17. Arrange below operators in the proper precedence
    ()
    **
    ~
    and 
    or
    &
    ^
    |
    /
    %
    //
    +
    - (Minus)
    - (Unary minus)
    *
    <<
    >>
    is
    is not
    !=
    not
    in
    not in
    >
    >=
    <
    <=
    ==

Precedence is used in an expression with more than one operator with different precedence to determine which operation to perform first. This all oprators have precedence from above to bottom.

| Operators | Meaning                                 |
| :---     | ---:                                   | 
|()	|Parentheses|
|** |	Exponent|
|+x, -x, ~x	| Unary plus, Unary minus, Bitwise NOT |
| *, /, //, % |	Multiplication, Division, Floor division, Modulus  |
| +, -	 | Addition, Subtraction |
| <<, >>  |	Bitwise shift operators|
|&	|Bitwise AND|
|^	| Bitwise XOR|
| I	|Bitwise OR|
| ==, !=, >, >=, <, <=, is, is not, in, not in	|  Comparisons, Identity, Membership operators|
| not | 	Logical NOT |
|and	| Logical AND |
|or	| Logical OR |

#### 18. For input a = 30 b = 20 c = 10 d = 5 print the output of below 
    ((a+b)*c/d)
    ((a+b)*(c/d))
    (a+(b*c)/d)

    Explain the precedence

In [20]:
a = 30 
b = 20 
c = 10 
d = 5

print("((a+b)*c/d): ", ((a+b)*c/d))
print("((a+b)*(c/d)): ", ((a+b)*c/d))
print("(a+(b*c)/d): ", ((a+b)*c/d))

((a+b)*c/d):  100.0
((a+b)*(c/d)):  100.0
(a+(b*c)/d):  100.0


Python has well-defined rules for specifying the order in which the operators in an expression are evaluated when the expression has several operators. For example, multiplication and division have a higher precedence than addition and subtraction. Precedence rules can be overridden by explicit parentheses.
Precedence is used in an expression with more than one operator with different precedence to determine which operation to perform first.

#### 19. WAP to create an array of 10 integers and display the array items. Access individual element through indexes.

In [21]:
array19 = np.arange(10)
print(array19)

for i in range(len(array19)):
    print(i,"th index has value: ", array19[i])

[0 1 2 3 4 5 6 7 8 9]
0 th index has value:  0
1 th index has value:  1
2 th index has value:  2
3 th index has value:  3
4 th index has value:  4
5 th index has value:  5
6 th index has value:  6
7 th index has value:  7
8 th index has value:  8
9 th index has value:  9


#### 20. WAP to append new element at the end of an array

In [22]:
array20 = np.arange(11)
np.append(array20, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### 21. WAP to reverse an array

In [23]:
array21 = np.arange(16)
np.flip(array21)

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 22. WAP to get the current memory address and the length in elements of the buffer used to hold an array's contents and also find the size of the memory buffer in bytes

In [24]:
from array import *
array22 = array('i', [45,67,23,98,12,56])
print("Bufferinfo: ", array22.buffer_info())
print("Memory Buffer in Bytes: ", (array22.buffer_info()[1] * array22.itemsize))

Bufferinfo:  (2778283941328, 6)
Memory Buffer in Bytes:  24


#### 23. WAP to get the number of occurrences of a specified element in an array

In [25]:
array23 = np.array([3,4,6,1,3,4,5,2,3,5,4,6,7,8,9,7,9,4,2,3,5,7,5,3,4,6,5,4,3])

set23 = set(array23)

for i in set23:
    if i in array23:
        print(i, "occurs", np.count_nonzero(array23 == i), "times")

1 occurs 1 times
2 occurs 2 times
3 occurs 6 times
4 occurs 6 times
5 occurs 5 times
6 occurs 3 times
7 occurs 3 times
8 occurs 1 times
9 occurs 2 times


#### 24. WAP to get largest element from array

In [26]:
array24 = np.array([34,78,34,56,98,76,89,65,67,44,67])

print(np.max(array24))
print(max(array24))
print(array24[array24.argmax()])

98
98
98


#### 25. WAP to get average of integers present in array

In [27]:
array25 = np.arange(1,11)
print("1d array: ", array25)
length1d = len(array25)
summation = array25.sum()

print("Average of array is: ", summation/length1d)

array25_2d = np.arange(1,10).reshape(3,3)
print("\n2d array: ", array25_2d)
addition = 0
length2d = 0
for i in np.nditer(array25_2d):   # element wise iteration
    addition += i 
    length2d += 1
    
print("Average of all elements in 2d array: ", addition/length2d)

1d array:  [ 1  2  3  4  5  6  7  8  9 10]
Average of array is:  5.5

2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Average of all elements in 2d array:  5.0


#### 26. Create an array of size 10 and insert new element at position 3 and 7 and update the position 2

In [28]:
array26 = np.arange(10)

array26 = np.insert(array26, 3, 24)
array26 = np.insert(array26, 7, 56)

array26[2] = 100

print(array26)

[  0   1 100  24   3   4   5  56   6   7   8   9]


#### 27. WAP to remove a elemnt from 5th position using the index from above array

In [29]:
array27 = array26.copy()

array27 = np.delete(array27, 5)
array27

array([  0,   1, 100,  24,   3,   5,  56,   6,   7,   8,   9])

#### 28. WAP to convert an array to an ordinary list with the same item

In [30]:
array28 = np.arange(20)

list28 = array28.tolist()

print(list28)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


#### 29. WAP to remove duplicates from an array

In [31]:
array29 = np.array([1,1,1,2,4,7,3,6,9,2,3,6,8,4,2,7])

print(np.unique(array29))

[1 2 3 4 6 7 8 9]


#### 30. WAP to get length of an array

In [32]:
array30 = np.arange(25)
print("Length of an array: ", len(array30))

Length of an array:  25


#### 31. WAP to find the missing number in a given array of numbers between 20 to 50

In [33]:
array31 = sorted(np.array([20,21,22,23,24,25,26,28,29,30,33,35,36,37,38,39,41,42,43,45,46,47,49,50]))
missing_numbers = []
for i in range(1, len(array31)):
    missed = array31[i-1] + 1
    if array31[i] != missed:
        missing_numbers.append(missed)
print("Missing numbers are: ", missing_numbers)

Missing numbers are:  [27, 31, 34, 40, 44, 48]


#### 32. WAP to rotate an array. Ex. Input array [1, 2, 3, 4, 5, 6, 7] Output [7, 6, 5, 4, 3, 2, 1]

In [34]:
array32 = np.array([1, 2, 3, 4, 5, 6, 7])

print(np.flip(array32))

[7 6 5 4 3 2 1]


#### 33. WAP to split the array and add the first part to the end

In [35]:
def splitArr(array33, split):
    array33 = array33[split:] + array33[:split]
    return array33
   
split = 5
array33 = [25,34,12,76,34,23,98,45,43]
print(splitArr(array33, split))

[23, 98, 45, 43, 25, 34, 12, 76, 34]


#### 34. WAP to find reminder of array multiplication divided by n

In [36]:
array34 = np.arange(23)
n = len(array34)
mul = 1
 
for i in array34:
    mul = mul * (i % n)
print(mul % n)

0


#### 35. WAP to check if given array is Monotonic

In [37]:
array35 = np.array([4,8,12,16,20,24])
if all(array35[i] >= array35[i+1] for i in range (len(array35)-1)):
    print("This seuqnce is Monotonically decreasing")
elif all(array35[i] <= array35[i+1] for i in range (len(array35)-1)):
    print("This sequence is Monotically increasing")
else:
    print("This sequence is not Monotic in nature")

This sequence is Monotically increasing


#### 36. Have the function ArrayMatching(strArr) read the array of strings stored in strArr which will contain only two elements, both of which will represent an array of positive integers. For example: if strArr is ["[1, 2, 5, 6]", "[5, 2, 8, 11]"], then both elements in the input represent two integer arrays, and your goal for this challenge is to add the elements in corresponding locations from both arrays. For the example input, your program should do the following additions: [(1 + 5), (2 + 2), (5 + 8), (6 + 11)] which then equals [6, 4, 13, 17]. Your program should finally return this resulting array in a string format with each element separated by a hyphen: 6-4-13-17.

If the two arrays do not have the same amount of elements, then simply append the remaining elements onto the new array (example shown below). Both arrays will be in the format: [e1, e2, e3, ...] where at least one element will exist in each array.

Examples

Input: ["[5, 2, 3]", "[2, 2, 3, 10, 6]"]

Output: 7-4-6-10-6

Input: ["[1, 2, 1]", "[2, 1, 5, 2]"]

Output: 3-3-6-2

In [38]:
def ArrayMatching(strArr):
    strArr_0 = []
    strArr_1 = []
    k = ''
    
    for i in (k.join(strArr[0].split(' '))).replace(",",' ').replace("[",'').replace(']','').split(' '):
        if i.isdigit():
            strArr_0.append(int(i))
    for i in (k.join(strArr[1].split(' '))).replace(",",' ').replace("[",'').replace(']','').split(' '):
        if i.isdigit():
            strArr_1.append(int(i))

    array1 = np.array(strArr_0)
    array2 = np.array(strArr_1)
    m = '' 
    
    if len(array1) < len(array2):
        new = array2.copy()
        new[:len(array1)] += array1
        m = ''
        for i in new:
            m += str(i) + '-'
        return m[:-1]
    elif len(array1) > len(array2):
        new = array1.copy()
        new[:len(array2)] += array2
        for i in new:
            m += str(i) + '-'
        return m[:-1]
    else:
        new = np.array(strArr_0) + np.array(strArr_1)
        for i in new:
            m += str(i) + '-'
        return m[:-1]
    
strArr = ["[5, 2, 3]", "[2, 2, 3, 10, 6]"]
print(ArrayMatching(strArr))
strArr = ["[1, 2, 5, 6]", "[5, 2, 8, 11]"]        
print(ArrayMatching(strArr)) 
strArr =  ["[1, 2, 1]", "[2, 1, 5, 2]"]
print(ArrayMatching(strArr))

7-4-6-10-6
6-4-13-17
3-3-6-2


#### 37. WAP to print output of below slicing options 

Input array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Operations 
	1. a[3:8]
	2. a[5:]
	3. a[:]

In [39]:
array37 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(array37[3:8])
print(array37[5:])
print(array37[:])

[4 5 6 7 8]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


#### 38. WAP to search en element 7 in the array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [40]:
array38 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.where(array38 == 7))

(array([6], dtype=int64),)


#### 39. WAP to add and multiply two 3x3 matrices.

In [41]:
import numpy as np
rows1 = int(input("Enter the number of rows for first matrix: ")) 
columns1 = int(input("Enter the number of columns for second: ")) 
matrix1= np.array([[input() for j in range(columns1)] for i in range(rows1)])
print(matrix1)

rows2 = int(input("Enter the number of rows for first matrix: ")) 
columns2 = int(input("Enter the number of columns for second: ")) 
matrix2 = np.array([[input() for j in range(columns2)] for i in range(rows2)])
print(matrix2)

sum_matrix = np.array([[0 for j in range(columns2)] for i in range(rows2)])

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        sum_matrix[i][j] += int(matrix1[i][j])+int(matrix2[i][j])
print(sum_matrix)      
multi_matrix = np.array([[0 for j in range(columns2)] for i in range(rows2)])
for i in range(len(matrix1)): 
    for j in range(len(matrix2[0])): 
        for k in range(len(matrix2)): 
            multi_matrix[i][j] += int(matrix1[i][k]) * int(matrix2[k][j])         
print(multi_matrix)

Enter the number of rows for first matrix: 3
Enter the number of columns for second: 3
1
2
3
4
5
6
7
8
9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
Enter the number of rows for first matrix: 3
Enter the number of columns for second: 3
1
2
3
4
5
6
7
8
9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


#### 40. WAP find a pair with a given sum in the array.

In [42]:
array40 = [3,4,5,7,1,3,5,8,6]
length = len(array40)
summation = 6
for x in range(0, length): 
    for y in range(x+1, length):
        if((array40[x]+array40[y])==summation):
            print(array40[x]," + ",array40[y]," = ",summation) 

3  +  3  =  6
5  +  1  =  6
1  +  5  =  6


#### 41. WAP to move all zeros to the end of an Array.

In [43]:
array41 = np.array([0, 5, 2,0,0,5,2,7,0,2,3])
print(sorted(array41,reverse=True))

index = 0
for i in range(0,len(array41)):
    if array41[i] != 0:
        array41[index] = array41[i]
        index += 1

for i in range(index, len(array41)):
        array41[index] = 0
        index += 1
print(array41)

[7, 5, 5, 3, 2, 2, 2, 0, 0, 0, 0]
[5 2 5 2 7 2 3 0 0 0 0]


#### 42. WAP to Move all zeros to the Start of an Array

In [44]:
array42 = np.array([0, 5, 2,0,0,5,2,7,0,2,3])
print(sorted(array42))

index = len(array42)-1
for i in range(len(array42)-1,-1,-1):
    if array42[i]!=0:
        array42[index]=array42[i]
        index -= 1

for i in range(index,-1,-1):
        array42[index]=0
        index -= 1
print(array42)

[0, 0, 0, 0, 2, 2, 2, 3, 5, 5, 7]
[0 0 0 0 5 2 5 2 7 2 3]


#### 43. WAP to Find the mean and median of an unsorted array.

In [45]:
array43 = np.array([64630, 11735, 14216, 99233, 14470, 4978, 73429, 38120, 51135, 67060])

nelements = len(array43)

sum_array = sum(array43)

mean_array = sum_array / nelements
print("Mean of array: ", mean_array)

array43.sort()

if nelements%2 == 0:
    median_arr_1 = array43[nelements//2]
    median_arr_2 = array43[nelements//2 - 1]
    median_array = (median_arr_1 + median_arr_2) / 2
else:
    median_array = array43[nelements//2]

print("Median of array: ", median_array)


Mean of array:  43900.6
Median of array:  44627.5


#### 44. WAP to Segregate 0s and 1s in an array.

In [46]:
array44 = np.array([0,0,0,0,0,1,1,0,1,1,1,1,0,0,0,1])
index = 0
for x in range(0,len(array44)):
    if array44[x] == 0:
        index += 1
for y in range(0, index):
        array44[y] = 0
for z in range(index, len(array44)):
        array44[z] = 1
print(array44)

[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1]


#### 41. WAP to find the median of two sorted arrays of different sizes.

In [49]:
array_41a = [2,8,5,6,1,9,6,3,8]
array_41b = [8,5,2,9,5,6,3,1,0,6,2,9]

total_length = len(array_41a) + len(array_41b)
final_array = [0]*total_length
first_iterator = 0
second_iterator = 0
iterator = 0
while iterator < total_length:
    if first_iterator < len(array_41a):
        final_array[iterator] = array_41a[first_iterator]
        first_iterator+=1
        iterator+=1
    if second_iterator < len(array_41b):
        final_array[iterator] = array_41b[second_iterator]
        second_iterator += 1
        iterator += 1

print(final_array)
if len(array_41a) % 2 == 1:
    median = final_array[len(array_41a) // 2]
    print("\nMedian= ", median)
else:
    median = (final_array[total_length // 2] + (final_array[(total_length // 2) - 1])) / 2.0
    print("\nMedian= ", median)

[2, 8, 8, 5, 5, 2, 6, 9, 1, 5, 9, 6, 6, 3, 3, 1, 8, 0, 6, 2, 9]

Median=  5


#### 42. WAP to find the median of two unsorted arrays.

In [53]:
array_42a = np.array([2,8,5,6,1])
array_42b = np.array([8,5,9,5])

total_length = len(array_42a) + len(array_42b)
final_array = [0]*total_length
first_iterator = 0
second_iterator = 0
iterator = 0
while iterator < total_length:
    if first_iterator < len(array_42a):
        final_array[iterator] = array_42a[first_iterator]
        first_iterator+=1
        iterator+=1
    if second_iterator < len(array_42b):
        final_array[iterator] = array_42b[second_iterator]
        second_iterator += 1
        iterator += 1


if len(array_42a) % 2 == 1:
    median = final_array[len(array_42a) // 2]
    print("\nMedian= ", median)
else:
    median = (final_array[total_length // 2] + (final_array[(total_length // 2) - 1])) / 2.0
    print("\nMedian= ", median)
    


Median=  8


#### 43. WAP to find the Max sum contiguous subarray.

In [54]:
array43 = np.array([3,4,1,9,3,6,2,8,0,1,6,5])

max_sum = 0
for x in range(0, len(array43)):
    for y in range(x, len(array43)):
        sum=0
        for z in range(x, y):
            summation += array43[z]
        if summation >= max_sum:
             max_sum = summation
print(max_sum)

1167


#### 44. WAP to find a pair with maximum product in an array.

In [56]:
array44 = [ 15, 3, 5, 30, 45] 

largest_prod = -9999999999

for i in range(len(array44)): 
    for j in range(len(array44) - 1): 
        for k in range(j + 1, len(array44)): 
            if (array44[j] * array44[k]==array44[i]): 
                largest_prod = max(largest_prod, array44[i]) 
                element1 = array44[k]
                element2 = array44[j]
                
print(largest_prod, "is the maximum product of", element1 , "x", element2)

45 is the maximum product of 3 x 15


#### 45. WAP to sort an array [9, 1, 5, 6, 8, 3, 2, 4, 7, 10]

In [57]:
array45 = np.array([9, 1, 5, 6, 8, 3, 2, 4, 7, 10])
array45 = sorted(array45)
print(array45)
sorted_array = [0 for i in range(len(array45))]
order = {"A": "Ascending Order", "D": "Descending Order"}
print(order)
want = input("Give your response as A/D: ")
if(want == "A"):
    print("We are printing the array in ", order['A'])
    for i in range(len(array45)):
        print(array45[i], end=" ")
elif(want == "D"):
    print("We are printing the array in ", order['D'])
    for i in range(len(array45)):
        sorted_array[len(array45)-1-i] = array45[i]
    for i in range(len(sorted_array)):
        print(sorted_array[i], end = " ")
else:
    pass

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
{'A': 'Ascending Order', 'D': 'Descending Order'}
Give your response as A/D: D
We are printing the array in  Descending Order
10 9 8 7 6 5 4 3 2 1 

#### 46. WAP to read and print a two dimensional array.

In [58]:
array46 = np.arange(1,37).reshape(6,6)
print(array46)

print("\nElements in the array are: ")
for x in array46:
    for y in x:
        print(y,end=' ')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Elements in the array are: 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 

#### 47. WAP to compare two arrays, print "Equal" if elements in array_1 are matching with elements in array_2

In [59]:
array_47a = np.arange(15).reshape(5,3)
array_47b = np.arange(15).reshape(5,3)

if np.array_equal(array_47a, array_47b):
    print("The array a and array b are equal")
else:
    print("The array a and b are not equal")

array_47c = np.arange(6).reshape(2,3)
array_47d = np.arange(6).reshape(3,2)

if np.array_equal(array_47c, array_47d):
    print("The array c and array d are equal")
else:
    print("The array c and d are not equal")

The array a and array b are equal
The array c and d are not equal


#### 48. WAP to find the common elements between two arrays 

In [60]:
array_48_a1d = np.array([1,2,3,4,5,6,7])
array_48_b1d = np.array([5,6,7,8,9,10])

print(np.intersect1d(array_48_a1d, array_48_b1d))

[5 6 7]


#### 49. WAP to add two matrices of the same size

In [61]:
import numpy as np
rows1 = int(input("Enter the number of rows for first matrix: ")) 
columns1 = int(input("Enter the number of columns for second: ")) 
matrix1= np.array([[input() for j in range(columns1)] for i in range(rows1)])
print(matrix1)

rows2 = int(input("Enter the number of rows for first matrix: ")) 
columns2 = int(input("Enter the number of columns for second: ")) 
matrix2 = np.array([[input() for j in range(columns2)] for i in range(rows2)])
print(matrix2)

sum_matrix = np.array([[0 for j in range(columns2)] for i in range(rows2)])

for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        sum_matrix[i][j] += int(matrix1[i][j])+int(matrix2[i][j])
print(sum_matrix)  

Enter the number of rows for first matrix: 2
Enter the number of columns for second: 2
1
2
3
4
[['1' '2']
 ['3' '4']]
Enter the number of rows for first matrix: 2
Enter the number of columns for second: 2
12
23
45
12
[['12' '23']
 ['45' '12']]
[[13 25]
 [48 16]]


#### 50. WAP to check whether a given matrix is Lower Triangular Matrix or not.

In [62]:
# as to check this, the matrix will be mxm (equal rows and columns)
# checking the position
low_tri_matrix = [[5,0,0,0],
                  [7,2,0,0],
                  [3,9,4,0],
                  [5,7,3,1]]

for x in range(0, len(low_tri_matrix)): 
    for y in range(x + 1, len(low_tri_matrix)): 
        if(low_tri_matrix[x][y] != 0):  
            print("This is not a lower triangular matrix")
print("This is a lower triangular matrix")

This is a lower triangular matrix


#### 51. WAP to print boundary elements of the matrix.

In [63]:
boundary_matrix = [[5,8,5,1],
                  [7,2,7,4],
                  [3,9,4,0],
                  [5,7,3,1]]

boundary_elements = []
for x in range(0, len(boundary_matrix)):
    for y in range(0, len(boundary_matrix)):
        if (x == 0):
            boundary_elements.append(boundary_matrix[x][y])
        elif (y == len(boundary_matrix) - 1):
            boundary_elements.append(boundary_matrix[x][y])
        elif (y == 0):
            boundary_elements.append(boundary_matrix[x][y])
        elif (y == len(boundary_matrix) - 1):
            boundary_elements.append(boundary_matrix[x][y])
        else:
            pass
print("The boundary elements of this matrix are: ", boundary_elements)

The boundary elements of this matrix are:  [5, 8, 5, 1, 7, 4, 3, 0, 5, 1]


#### 52. WAP to create a matrix and fill it with prime numbers.

In [65]:
import math 
import numpy as np

def Prime(n):  
    for i in range(2,n//2+1):  
        if(n%i==0):  
            return(0)  
    return(1)

N = int(input("How many elements are there in your matrix: "))

while True:
    if math.sqrt(N) == int(math.sqrt(N)):
        print("Acceptable range")
        x = 2 
        list2 = [] 
        while(1):  
            if(Prime(x)):  
                list2.append(x) 
                if(len(list2) == N): 
                    break 
            x += 1 

        matrix_new = np.array(list2).reshape(int(math.sqrt(N)),int(math.sqrt(N)))
        print(matrix_new)
        break
    else:
        N = int(input("Try Again! Give a perfect square How many elements are there in your matrix: "))

How many elements are there in your matrix: 15
Try Again! Give a perfect square How many elements are there in your matrix: 35
Try Again! Give a perfect square How many elements are there in your matrix: 24
Try Again! Give a perfect square How many elements are there in your matrix: 25
Acceptable range
[[ 2  3  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]]


#### 53. WAP to merge and sort two one dimensional arrays.

In [66]:
array1 = [5,6,2,8]
array2 = [0,2,3,1]

new = [np.nan for i in range(len(array1)+len(array2))]
array1_iterator, array2_iterator, new_iterator = 0, 0, 0
while (array1_iterator < len(array1)):
    new[new_iterator] = array1[array1_iterator]
    array1_iterator += 1
    new_iterator += 1
while (array2_iterator < len(array2)):
    new[new_iterator] = array2[array2_iterator]
    array2_iterator += 1
    new_iterator += 1
    
print("The new merged and sorted array: ", sorted(new))

The new merged and sorted array:  [0, 1, 2, 2, 3, 5, 6, 8]


#### 54. WAP find union and intersection of 2 arrays

In [67]:
array1 = [4,5,6,1,9,6,2]
array2 = [9,1,4,7,5,6,8]

print("Intersection of two arrays: ", list(set(array1) | set(array2)))
print("Union of two arrays: ", list(set(array1) & set(array2)))

Intersection of two arrays:  [1, 2, 4, 5, 6, 7, 8, 9]
Union of two arrays:  [1, 4, 5, 6, 9]


#### 55. WAP to find whether given number x appears more than n/2 times in a sorted array of size n

In [68]:
array3 = sorted(np.array([3,3,3,4,4,4,4,2,6,6,8,8,9,9,3,3]))
set3 = set(array3)
for i in set3:
    if array3.count(i) > i/2:
        print(i, "appears more than", round(float(i/2),2), "times.", "Occurs ", array3.count(i), "times")
    else:
        #print(i, "does not appears more than", round(float(i/2),2), "times.", "Occurs: ", array3.count(i), "times")
        pass

3 appears more than 1.5 times. Occurs  5 times
4 appears more than 2.0 times. Occurs  4 times


#### 56. WAP to accept a matrix of order n*m and interchange the diagonals

In [69]:
rows = int(input("Enter the number of rows:")) 
columns = int(input("Enter the number of columns:")) 
matrix= np.array([[input() for j in range(columns)] for i in range(rows)])
print(matrix)

n = columns - 1
for i in range(len(matrix)):
    for j in range(len(matrix)):
        if i == j:
            temp = matrix[i][j]
            matrix[i][j] = matrix[i][n]
            matrix[i][n] = temp
            n -= 1
print(matrix)

Enter the number of rows:3
Enter the number of columns:3
1
2
3
4
5
6
7
8
9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[['3' '2' '1']
 ['4' '5' '6']
 ['9' '8' '7']]


#### 57. WAP to perform matrix multiplication

In [70]:
import numpy as np
rows1 = int(input("Enter the number of rows for first matrix: ")) 
columns1 = int(input("Enter the number of columns for second: ")) 
matrix1= np.array([[input() for j in range(columns1)] for i in range(rows1)])
print(matrix1)

rows2 = int(input("Enter the number of rows for first matrix: ")) 
columns2 = int(input("Enter the number of columns for second: ")) 
matrix2 = np.array([[input() for j in range(columns2)] for i in range(rows2)])
print(matrix2)

multi_matrix = np.array([[0 for j in range(columns2)] for i in range(rows2)])

for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
            multi_matrix[i][j] += int(matrix1[i][k])*int(matrix2[k][j])
        

print(multi_matrix)
#for i in range(len(matrix1)):
    #for j in range(len(matrix1)):
        #for k in range(len(matrix1)):
            #multi_matrix[i][j] = multi_matrix[i][j] + int(matrix1[i][k])*int(matrix2[k][j])
#print(multi_matrix)

Enter the number of rows for first matrix: 3
Enter the number of columns for second: 3
1
2
3
4
5
6
7
8
9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
Enter the number of rows for first matrix: 3
Enter the number of columns for second: 3
1
2
3
4
5
6
7
8
9
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


###### 58. WAP to perform a binary search in a given array

In [71]:
def bin_search(array , to_find):   
    mini = 0
    maxi = len(array) - 1
    got_the_find = False
    while(mini <= maxi and not got_the_find):
        centre = (mini + maxi)//2
        if array[centre] == to_find:
            got_the_find = True
         
        else:
            if to_find < array[centre]:
                maxi = centre - 1
            else:
                mini = centre + 1

    if got_the_find == True:
        return("At index {} the element {} is present".format(to_find, centre))
    else:
        return("Element {} is not present".format(to_find))
     
array = [1,2,3,4,5,6,7,8,9]
to_find=3
print(bin_search(array,to_find))
to_find=51
print(bin_search(array,to_find))

At index 3 the element 2 is present
Element 51 is not present


#### 59. WAP to get median of two sorts arrays

In [72]:
array_42a = np.array([2,8,5,6,1])
array_42b = np.array([8,5,9,5])

total_length = len(array_42a) + len(array_42b)
final_array = [0]*total_length
first_iterator = 0
second_iterator = 0
iterator = 0
while iterator < total_length:
    if first_iterator < len(array_42a):
        final_array[iterator] = array_42a[first_iterator]
        first_iterator+=1
        iterator+=1
    if second_iterator < len(array_42b):
        final_array[iterator] = array_42b[second_iterator]
        second_iterator += 1
        iterator += 1

final_array = sorted(final_array)

if len(array_42a) % 2 == 1:
    median = final_array[len(array_42a) // 2]
    print("\nMedian= ", median)
else:
    median = (final_array[total_length // 2] + (final_array[(total_length // 2) - 1])) / 2.0
    print("\nMedian= ", median)
    
print(final_array)


Median=  5
[1, 2, 5, 5, 5, 6, 8, 8, 9]


#### 60. WAP to add list of elements to a given set

Input
set_1 = {"a", "b", "c"}
list_1 = ["b", "d", "e"]

In [73]:
set_1 = {"a", "b", "c"}
list_1 = ["b", "d", "e"]
set_2 = set_1.union(set(list_1))
print("The updated set is: ", set_2)

The updated set is:  {'d', 'c', 'b', 'e', 'a'}


#### 61. Create the set and print its element values, type and id

In [74]:
set_2 = {'b', 3, 'e', 5.8, 'a', True}

for i in set_2:
    print("The element: ", i, "\nType of element: ", type(i), "\nMemory Location Id: ", id(i), "\n")

The element:  True 
Type of element:  <class 'bool'> 
Memory Location Id:  140708057900880 

The element:  3 
Type of element:  <class 'int'> 
Memory Location Id:  140708058183520 

The element:  5.8 
Type of element:  <class 'float'> 
Memory Location Id:  2778301235760 

The element:  a 
Type of element:  <class 'str'> 
Memory Location Id:  2777977077296 

The element:  b 
Type of element:  <class 'str'> 
Memory Location Id:  2777977065648 

The element:  e 
Type of element:  <class 'str'> 
Memory Location Id:  2777975662064 



#### 62. Create set using set function

In [75]:
list_2 = ['England', 1997, 'Runner Up', 14.5]
set_3 = set(list_2)
print("The set is: ", set_3)

The set is:  {'Runner Up', 1997, 'England', 14.5}


#### 63. Find ways to create an empty set

In [76]:
set_empty = set()
print("This is an empty set: ", set_empty)

This is an empty set:  set()


#### 64. Create set and add new element into it and update existing elements. Notedown the difference between add and update functions

In [77]:
# update: it can update the existing set with sequence added as argument
rainbow_colors = {'Orange','Green','Blue'}
rainbow_colors.update(['Red','Yellow','Violet','White'])
print(rainbow_colors)

# add : we can pass only one element as argument
roll_no = {101, 102, 103, 104}
roll_no.add('105')
print(roll_no)

# update: we can pass list, string, tuple, dictionary, set as argument.
# if the update function is void, it will not return anything.
# if the argument is dictionary, it will update keys as elements of set.

# add: we can pass a element as argument.
# if the element is already present, it will not add it again. (behaviour of set)

# Note: while using these functions order of the elements can be different.

{'Green', 'White', 'Red', 'Blue', 'Violet', 'Yellow', 'Orange'}
{'105', 101, 102, 103, 104}


#### 65. Create a set and perform below operations on it 

	copy
	pop
	remove 
	discard
	clear

In [78]:
set_4 = {50, 51, 52, 53, 54, 55}

set_5 = set_4.copy()
print("Created a copy of set_4 as set_5: ", set_5, "\nMemory Location set_4: ", id(set_4), "\nand for set_5", id(set_5))

print("\nRemoves an arbitary element and give it as result: ", set_4.pop())

set_5.remove(52)
print("\nremove() Removes a specific element given as argument: ", set_5)

set_5.discard(50)
print("\ndiscard() Removes a specific element (only if it is present): ", set_5)

print("Discard returns None if element is not present: ", set_5.discard(90))

print("\nclear() Removes all the elements from the set: ", set_4.clear())

Created a copy of set_4 as set_5:  {50, 51, 52, 53, 54, 55} 
Memory Location set_4:  2778284122176 
and for set_5 2778284125088

Removes an arbitary element and give it as result:  50

remove() Removes a specific element given as argument:  {50, 51, 53, 54, 55}

discard() Removes a specific element (only if it is present):  {51, 53, 54, 55}
Discard returns None if element is not present:  None

clear() Removes all the elements from the set:  None


#### 66. Create two sets and perform below operations

	union
	intersaction
	difference
	symmetric_difference
	symmetric_difference_update
	issuperset
	issubset
	isdisjoint
	intersection_update

In [79]:
set_6 = {4, 'a', 'b', 2, 'u', 'p'}
set_7 = {'b', 'd', 2 , 'a', 'c', 'u' , 4,}
set_8 = {'a', 'b', 'c'}

print("set_6 union set_7: ", set_6.union(set_7))
print("set_6 intersection set_7: ", set_6.intersection(set_7))
print("set_6 difference set_7: ", set_6.difference(set_7))
print("set_6 symmetric_difference set_7: ", set_6.symmetric_difference(set_7), "elements out of intersection")

print("\nset_6 symmetric_difference_update set_7: ", set_6.symmetric_difference_update(set_7), "set_6: ", set_6, "set_7: ", set_7)

print("\nset_6 is superset of set_7? ", set_6.issuperset(set_7))

print("\nset_8 is subset of set_8? ", set_8.issubset(set_7))

print("\nset_6 and set_7 are disjoint? ", set_6.isdisjoint(set_7))

set_8.intersection_update(set_7)
print("\nset_8 intersection_update set_7: ", set_8.intersection_update(set_7), "set_8: ", set_8, "set_7: ", set_7)

set_6 union set_7:  {2, 4, 'c', 'd', 'a', 'u', 'p', 'b'}
set_6 intersection set_7:  {2, 4, 'a', 'u', 'b'}
set_6 difference set_7:  {'p'}
set_6 symmetric_difference set_7:  {'p', 'c', 'd'} elements out of intersection

set_6 symmetric_difference_update set_7:  None set_6:  {'c', 'd', 'p'} set_7:  {2, 4, 'c', 'd', 'a', 'u', 'b'}

set_6 is superset of set_7?  False

set_8 is subset of set_8?  True

set_6 and set_7 are disjoint?  False

set_8 intersection_update set_7:  None set_8:  {'b', 'a', 'c'} set_7:  {2, 4, 'c', 'd', 'a', 'u', 'b'}


#### 67. Create a set and apply menbership operations on it (in and not in)

In [80]:
set_9 = {'a', 'e', 'i', 'o'}

if 'a' in set_9:
    print("a is present in vowel list")

if 'u' not in set_9:
    print("u is not present in vowel list")

a is present in vowel list
u is not present in vowel list


#### 68. What is set comprehension and how it works. Explain is detail with example

In [81]:
# we can create a set inside set() function or curly braces. 
# Basically the sequence is created using loops and conditional statements.

print("Square of even numbers upto 10")
print(set(x*2 for x in range(11) if x%2 == 0))

# In above example we are initiating a for loop over range(11).
# checking it with conditional statement that if the number is even.
# at start of the expression, x*2 that is square it.
# and this whole comprehensive expression is written in the set() so it will be a set of elements satisfying this condition.

# another way 

print("\nexpression in curly braces: ", {x*2 for x in range(11) if x%2 == 0})

Square of even numbers upto 10
{0, 4, 8, 12, 16, 20}

expression in curly braces:  {0, 4, 8, 12, 16, 20}


#### 69. What is nested set comprehension and how it works. Explain is detail with example.

In [82]:
# nested set comprehension: The inner sets, needs to be frozen sets, or you will get an error.
# A frozen set is just like a set, although sets are mutable and frozen sets are not. 
# Sets are changeable, which makes them unhashable, and therefore they cannot exist as items 
# within a larger set unless they are frozen. Luckily, we can simply make sets into frozen sets 
# by enclosing them in the frozenset() function.

organization = "Chistats Private Limited, a data science company"
chars = organization.split()
vowels = ['a', 'e', 'i', 'o', 'u']
consonants = {frozenset(
    {letter for letter in word if letter not in vowels}) for word in chars}
print(consonants)

{frozenset({'d', 't'}), frozenset({'L', 'd', 'm', 't', ','}), frozenset({'v', 'P', 't', 'r'}), frozenset({'p', 'c', 'n', 'y', 'm'}), frozenset({'n', 's', 'c'}), frozenset(), frozenset({'C', 'h', 't', 's'})}


#### 70. What is frozenset, explain in detial with example

In [83]:
# Frozenset is a class with the characteristics of a set, but once its elements have been assigned, 
# they cannot be changed. Tuples can be seen as immutable lists, while frozensets can be seen as immutable sets.

# Sets are mutable and unhashable, which means we cannot use them as dictionary keys. 
# Frozensets are hashable and we can use them as dictionary keys.

set_10 = {1,2,3,4}
set_11 = frozenset({1,2,3,4})

set_10.add(8)
print(set_10)

set_11.add(8)
print(set_11)

{1, 2, 3, 4, 8}


AttributeError: 'frozenset' object has no attribute 'add'

In [84]:
set_12 = frozenset({1,2,3,4})
 
print(set_12)
 
copy = set_12.copy()
print("Copy of set_12: ", copy)

print("23 in set_12?", 3 in set_12)
 
print("23 not in set_12? ", 23 not in set_12)

frozenset({1, 2, 3, 4})
Copy of set_12:  frozenset({1, 2, 3, 4})
23 in set_12? True
23 not in set_12?  True


## Thank You!